name: Build

on:
  push:

permissions:
  contents: read # Fetch code (actions/checkout)
  packages: write # Upload and publish packages to GitHub Packages

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:      
    - name: Prepare
      env:
        S3_CREDS: ${{ secrets.S3_CREDS }}
        S3_BUCKET: lineage-gh-ci
      run: |
        sudo apt update
        sudo apt install -y \
          bc \
          bison \
          build-essential \
          ccache \
          curl \
          flex \
          g++-multilib \
          gcc-multilib \
          git \
          git-lfs \
          gnupg \
          gperf \
          imagemagick \
          lib32ncurses5-dev \
          lib32readline-dev \
          lib32z1-dev \
          libdw-dev \
          libelf-dev \
          libncurses5 \
          libncurses5-dev \
          libsdl1.2-dev \
          libssl-dev \
          libxml2 \
          libxml2-utils \
          lz4 \
          lzop \
          pngcrush \
          protobuf-compiler \
          python3-protobuf \
          rsync \
          s3fs \
          schedtool \
          squashfs-tools \
          xsltproc \
          zip \
          zlib1g-dev
        echo "${S3_CREDS}" > ${HOME}/.passwd-s3fs
        chmod 600 ${HOME}/.passwd-s3fs
        sudo mkdir -p /mnt/s3
        sudo s3fs "${S3_BUCKET}" /mnt/s3 -o passwd_file=${HOME}/.passwd-s3fs -o use_path_request_style,allow_other,use_cache=/tmp/s3,url=https://s3.ca-east-tor.io.cloud.ovh.net/
        touch /mnt/s3/.ready
        mkdir -p /mnt/s3/bin
        mkdir -p /mnt/s3/android/lineage
        curl https://storage.googleapis.com/git-repo-downloads/repo > /mnt/s3/bin/repo
        chmod a+x /mnt/s3/bin/repo
        echo "PATH=/mnt/s3/bin:$PATH" >> "${GITHUB_ENV}"
        python3 --version
    - name: Download lineage
      working-directory: /mnt/s3/android/lineage
      run: |
        repo init -u https://github.com/LineageOS/android.git -b lineage-22.2 --git-lfs --no-clone-bundle --verbose
        repo sync --verbose
        cat > .repo/local_manifests/fairphone_FP6.xml <<EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <manifest>
          <!-- Device trees -->
          <project name="ArianK16a/android_device_fairphone_FP6" path="device/fairphone/FP6" remote="github" revision="lineage-22.2" />

          <!-- Kernel -->
          <project name="ArianK16a/android_kernel_fairphone_sm7635" path="kernel/fairphone/sm7635" remote="github" revision="lineage-22.2"  />
          <project name="ArianK16a/android_kernel_fairphone_sm7635-devicetrees" path="kernel/fairphone/sm7635-devicetrees" remote="github" revision="lineage-22.2"  />
          <project name="ArianK16a/android_kernel_fairphone_sm7635-modules" path="kernel/fairphone/sm7635-modules" remote="github" revision="lineage-22.2"  />

          <!-- Vendor - not pushed anywhere yet-->
          <!-- <project name="ArianK16a/proprietary_vendor_fairphone_FP6" path="vendor/fairphone/FP6" remote="mainlining" revision="lineage-22.2" /> -->

          <project name="ArianK16a/android_packages_apps_AlertSlider" path="packages/apps/AlertSlider" remote="github" revision="lineage-22.2" />
        </manifest>
        EOF
    - name: Prepare vendor
      working-directory: /mnt/s3/android/lineage/device/fairphone/FP6
      run: |
        ./extract-files.py https://fairphone-android-builds.ams3.digitaloceanspaces.com/FP6/A15/FP6.QREL.15.122.0.20250718182448_VS1E-factory.zip
    - name: Cleanup
      if: always() && vars.AUTO_CLEANUP != null
      env:
        S3_CREDS: ${{ secrets.S3_CREDS }}
      run: |
        python3 -m pip install awscli
        export AWS_ACCESS_KEY_ID=$(echo $S3_CREDS | cut -d: -f 1)
        export AWS_SECRET_ACCESS_KEY=$(echo $S3_CREDS | cut -d: -f 2)
        export AWS_REGION=us-west-2 # Unused
        aws s3 rm --endpoint-url https://s3.ca-east-tor.io.cloud.ovh.net/  --recursive lineage-gh-ci/


